export const ADD_PROJECT = "ADD_PROJECT";
export const ADD_REPORT = "ADD_REPORT";
export const SET_SELECTED_PROJECT = "SET_SELECTED_PROJECT";
export const SET_CUR_TAB_POS = "SET_CUR_TAB_POS";
export const SET_SELECTED_PROPOSAL = "SET_SELECTED_PROPOSAL";